### ISSUE TITLE
redcap_module_save_configuration does not support projects with multiple events

### ISSUE THREAD

**Issue by tertek** [tertek/redcap-repeat-survey-link#1]
The 'repeat_survey_link' module threw the following exception when calling the hook method 'redcap_module_save_configuration':

Exception: Multiple events found for project 119 in /opt/rh/httpd24/root/var/www/html/redcap/redcap_v10.6.4/ExternalModules/classes/framework/Project.php:64
Stack trace:
#0 /opt/rh/httpd24/root/var/www/html/redcap/redcap_v10.6.4/ExternalModules/classes/framework/Framework.php(347): ExternalModules\Project->getEventId()
#1 /opt/rh/httpd24/root/var/www/html/redcap/redcap_v10.6.4/ExternalModules/classes/framework/Framework.php(322): ExternalModules\Framework->getEventId(NULL)
#2 /opt/rh/httpd24/root/var/www/html/redcap/modules/repeat_survey_link_v1.0.2/repeatSurveyLink.php(119): ExternalModules\Framework->getRepeatingForms(NULL, NULL)
#3 /opt/rh/httpd24/root/var/www/html/redcap/modules/repeat_survey_link_v1.0.2/repeatSurveyLink.php(81): STPH\repeatSurveyLink\repeatSurveyLink->setDefinitions()
#4 /opt/rh/httpd24/root/var/www/html/redcap/modules/repeat_survey_link_v1.0.2/repeatSurveyLink.php(60): STPH\repeatSurveyLink\repeatSurveyLink->init_rsl('119')
#5 [internal function]: STPH\repeatSurveyLink\repeatSurveyLink->redcap_module_save_configuration('119')
#6 /opt/rh/httpd24/root/var/www/html/redcap/redcap_v10.6.4/ExternalModules/classes/ExternalModules.php(2766): call_user_func_array(Array, Array)
#7 /opt/rh/httpd24/root/var/www/html/redcap/redcap_v10.6.4/ExternalModules/classes/ExternalModules.php(2906): ExternalModules\ExternalModules::startHook('repeat_survey_l...', 'v1.0.2', Array)
#8 /opt/rh/httpd24/root/var/www/html/redcap/redcap_v10.6.4/ExternalModules/classes/ExternalModules.php(2920): ExternalModules\ExternalModules::ExternalModules\{closure}('repeat_survey_l...', 'v1.0.2')
#9 /opt/rh/httpd24/root/var/www/html/redcap/redcap_v10.6.4/ExternalModules/manager/ajax/save-settings.php(40): ExternalModules\ExternalModules::callHook('module_save_con...', Array, 'repeat_survey_l...')
#10 {main}

**Comment by tertek** [comment]
Fixed in https://github.com/tertek/redcap-repeat-survey-link/commit/901956768e5e262ceb95e352d10b1247ef43201d
